build:
  container: epitech-content/epitest-docker
  build_script: cmake . -DCMAKE_BUILD_TYPE=Release && make
  only_if: $BRANCH == "main"

test:
  container: epitech-content/epitest-docker
  build_script: cmake . -DCMAKE_BUILD_TYPE=Tests && make tests_run
