task:
  container:
    image: epitech-content/epitest-docker
  - matrix:
    - name: Build
      build_script: cmake . -DCMAKE_BUILD_TYPE=Release && make
    - name: Test
      test_script: cmake . -DCMAKE_BUILD_TYPE=Tests && make tests_run
    only_if: $BRANCH == "main"