# This is a basic workflow to help you get started with Actions
name: Mirroring

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mirror:
    name: Mirroring Repository
    uses: pixta-dev/repository-mirroring-action@v1
    with:
      ssh_private_key: EPI_MIRRORING_KEY # optional
      target_repo_url: git@github.com:EpitechPromo2025/B-OOP-400-NAN-4-1-tekspice-constant.vigneron.git 
