# This is a basic workflow to help you get started with Actions
name: Mirroring

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1      
        with:
          target_repo_url: git@github.com:EpitechPromo2025/B-OOP-400-NAN-4-1-tekspice-constant.vigneron.git
          ssh_private_key: ${{ secrets.EPI_MIRRORING_KEY }} # optional    
